### ISSUE TITLE
Minium Condenser is not condensing items

### ISSUE THREAD

**Issue by Ricket** [Lomeli12/SimpleCondenser#10]
I set my condenser to ignore redstone and always condense:

![2015-10-23 21_30_32-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10708180/58fe6ace-79cd-11e5-96ce-3604aa4fce04.png)

I condensed an octuple cobblestone:

![2015-10-23 21_31_26-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10708185/7327fcc6-79cd-11e5-8ce3-51e7418a9def.png)

I learned about gold ingots:

![2015-10-23 21_32_15-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10708193/92aae90a-79cd-11e5-9eb1-37282909942c.png)

I have a gold ingot:

![2015-10-23 21_32_44-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10708197/a0e41686-79cd-11e5-8861-a5b04cb6120e.png)

I'm not receiving gold ingots:

![2015-10-23 21_33_07-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10708203/aeb2aaa2-79cd-11e5-864f-de3f358b9c5f.png)

**Comment by Ricket** [comment]
Just confirmed that it's the same story for the other types of condensers, and other items. It's also not correlated to the amount of EE (i.e. it's not an integer overflow) -- even with low amounts, for example I would set gold ingots as the item to create and deposit one diamond for just a little EE, still no ingots were made. And no diamonds made when I deposited enough EE for them. It seems the condenser is not making anything at all, it's totally broken.

**Comment by Lomeli12** [comment]
This is a problem with the Energy Value System, NOT Simple Condensers. Notice how gold has an exchange value of 0 instead of the usual 2,048.
https://github.com/pahimar/Equivalent-Exchange-3/issues/990
