### ISSUE TITLE
Suuri star showing up as unnamed and causing a crash when trying to make geladen star

### ISSUE THREAD

**Issue by HyunMi027** [Lomeli12/SimpleCondenser#12]
Crash report: http://paste.ubuntu.com/23675953/

Edited to use a pastebin

**Comment by Lomeli12** [comment]
You're using a newer version of EE3, which no longer has a class in its API that Simple Condenser references. As I'm no longer supporting 1.7, I won't fix this. Downgrade to an earlier version of EE3 (0.3.0.546 or lower)
