### ISSUE TITLE
Condenser doesn't recognize items

### ISSUE THREAD

**Issue by bluemoon1993** [Lomeli12/SimpleCondenser#8]
Using the FTB Horizons: Daybreaker modpack, version 1.1.0.  EE3 is 1.7.10-0.3.507, SC is 1.2.0, LomLib is 3.2.0.

The verdant condenser doesn't recognize the items in the Tome of Alchemical Knowledge. I learn in the Research Table, for example, cobblestone, and it shows up inside the Tome (it has an energy value of 0, not sure if thats supposed to happen). I then go to the Verdant Condenser, put the book on the right, cobblestone on the left, and it converts items into EE, but does not convert into cobblestone. I actually converts even cobblestone into energy, so either it is not recognizing the item on the left or the fact that I have already researched it.

Want printscreens or logs of any kind? Can provide both server and client logs.

**Comment by Lomeli12** [comment]
That's a bug on EE3 side, not SC. Best way to deal with it is to delete the item from your tome (ee3 has a command to forget items) and relearn it.

**Comment by bluemoon1993** [comment]
but my tome is reset everytime i relog in the server

**Comment by Lomeli12** [comment]
Again, an EE3 issue. SC just LOOKS at what you've learned. It doesn't edit it in any way. https://github.com/pahimar/Equivalent-Exchange-3/issues/945

**Comment by bluemoon1993** [comment]
I fixed this by learning things in SinglePlayer (where EE3 saves the player knowledge). The file was then migrated to the server and SC can work from now on. Let's hope EE3 fixes this for other players out there.
